title: "Centam Select"
description: "Curated Central American Coffee from the Heart of Central America"

url: "https://abinitiativesllc.github.io"
baseurl: "/abinitiativesllc"

remote_theme: "rohanchandra/type-theme"

navbar_links:
  About: "/abinitiativesllc/about"
  Contact: "/abinitiativesllc/contact"

timezone: "America/New_York"
